export const FETCH_MOVIE_EDIT_RESQUESS= "FETCH_MOVIE_EDIT_RESQUESS"
export const FETCH_MOVIE_EDIT_SUCCESS = "FETCH_MOVIE_EDIT_SUCCESSH_"
export const FETCH_MOVIE_EDIT_FAIL= "FETCH_MOVIE_EDIT_FAIL"

export const GET_INFOR_MOVIE= "GET_INFOR_MOVIE";
