export const FETCH_MOVIE_SEAT_SUCCESS = "FETCH_MOVIE_SEAT_SUCCESS";
export const FETCH_MOVIE_SEAT_FAIL = "FETCH_MOVIE_SEAT_FAIL";
export const DAT_VE = "DAT_VE";
export const DAT_VE_HOAN_TAT = "DAT_VE_HOAN_TAT";
export const SET_THONG_TIN_NGUOI_DUNG = "SET_THONG_TIN_NGUOI_DUNG";
