export const FETCH_GET_USER_SUCCESS = "FETCH_GET_USER_SUCCESS";
export const FETCH_GET_USER_FAIL = "FETCH_GET_USER_FAIL";
export const FETCH_UPDATE_USER_SUCCESS = "FETCH_UPDATE_USER_SUCCESS";
export const FETCH_UPDATE_USER_FAIL = "FETCH_UPDATE_USER_FAIL";
